# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 19:14
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='html_description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='html_description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
