# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180716_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Multiplier'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='subjobs',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Multiplier'),
        ),
        migrations.AlterField(
            model_name='subjobs',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subjobs',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
